; G-Code generated by Simplify3D(R) Version 3.1.1
; May 13, 2017 at 11:11:57 PM
; Settings Summary
;   processName,Process1
;   applyToModels,20mm_cube
;   profileName,VinylCutter (modified)
;   profileVersion,2016-08-12 17:56:37
;   baseProfile,Monoprice Maker Select(2) (modified)
;   printMaterial,
;   printQuality,
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.4
;   extruderAutoWidth,0
;   extruderWidth,0.4
;   extrusionMultiplier,0.96
;   extruderUseRetract,1
;   extruderRetractionDistance,1
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,20
;   extruderRetractionSpeed,1500
;   extruderUseCoasting,0
;   extruderCoastingDistance,1.6
;   extruderUseWipe,0
;   extruderWipeDistance,2
;   primaryExtruder,0
;   layerHeight,0.15
;   topSolidLayers,0
;   bottomSolidLayers,0
;   perimeterOutlines,1
;   printPerimetersInsideOut,1
;   startPointOption,2
;   startPointOriginX,0
;   startPointOriginY,0
;   startPointOriginZ,300
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,100
;   firstLayerWidthPercentage,150
;   firstLayerUnderspeed,0.5
;   useRaft,0
;   raftExtruder,0
;   raftLayers,1
;   raftOffset,1
;   raftSeparationDistance,0.14
;   raftInfill,90
;   disableRaftBaseLayers,0
;   useSkirt,0
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,2
;   skirtOffset,0.8
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Grid
;   externalInfillPattern,Rectilinear
;   infillPercentage,0
;   outlineOverlapPercentage,20
;   infillExtrusionWidthPercentage,100
;   minInfillLength,5
;   infillLayerInterval,1
;   infillAngles,45,-45
;   overlapInfillAngles,1
;   generateSupport,0
;   supportExtruder,0
;   supportInfillPercentage,30
;   supportExtraInflation,0
;   denseSupportLayers,0
;   denseSupportInfillPercentage,70
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,45
;   supportAngles,0
;   temperatureName,Primary Extruder
;   temperatureNumber,0
;   temperatureSetpointCount,1
;   temperatureSetpointLayers,1
;   temperatureSetpointTemperatures,190
;   temperatureStabilizeAtStartup,1
;   temperatureHeatedBed,0
;   temperatureRelayBetweenLayers,0
;   temperatureRelayBetweenLoops,0
;   fanLayers
;   fanSpeeds
;   blipFanToFullPower,0
;   adjustSpeedForCooling,0
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,100
;   increaseFanForBridging,0
;   bridgingFanSpeed,100
;   use5D,1
;   relativeEdistances,0
;   allowEaxisZeroing,0
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,210
;   strokeYoverride,200
;   strokeZoverride,180
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,1
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,1
;   printerModelsOverride
;   startingGcode,G28,
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,G28 X0 ; home X-axis
;   exportFileFormat,gcode
;   celebration,0
;   celebrationSong,Looney Toons
;   postProcessing,
;   defaultSpeed,4200
;   outlineUnderspeed,0.5
;   solidInfillUnderspeed,0.5
;   supportUnderspeed,0.8
;   rapidXYspeed,4800
;   rapidZspeed,1000
;   minBridgingArea,50
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,1
;   filamentDiameter,1.75
;   filamentPricePerKg,20
;   filamentDensity,1.25
;   useMinPrintHeight,0
;   minPrintHeight,2.5
;   useMaxPrintHeight,1
;   maxPrintHeight,0.15
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,0
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,1
;   useRetractionMinTravel,0
;   retractionMinTravel,3
;   retractWhileWiping,0
;   onlyWipeOutlines,1
;   avoidCrossingOutline,0
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   allowThinWallGapFill,1
;   thinWallAllowedOverlapPercentage,50
;   horizontalSizeCompensation,0
G90
M82
M104 S190 T0
M109 S190 T0
G28
G1 E-1.0000 F1500

; layer 1, Z = 0.15
T0
; tool H0.150 W0.600
; outer perimeter
G1 X90.300 Y90.300 F4800
G1 Z20.150 F1000
G1 Z0.150 F1000
G1 E0.0000 F450
G1 X109.700 Y90.300 E0.6969 F1050
G1 X109.700 Y109.700 E1.3937
G1 X90.300 Y109.700 E2.0906
G1 X90.300 Y90.300 E2.7875
G1 E1.7875 F1500
; layer end
G28 X0 Z1 ; home X-axis
; Build Summary
;   Build time: 0 hours 0 minutes
;   Filament length: 2.8 mm (0.00 m)
;   Plastic volume: 6.70 mm^3 (0.01 cc)
;   Plastic weight: 0.01 g (0.00 lb)
;   Material cost: 0.00
